Add `netmask-length`.

diff --git a/src/lib/cidr-calc b/src/lib/cidr-calc
--- a/src/lib/cidr-calc
+++ b/src/lib/cidr-calc
@@ -354,6 +354,30 @@ function command_address-words {
     jval --raw cidr:json="${cidr}" '$cidr.address | map(tostring) | join(" ")'
 }
 
+# Command: Gets the total number of bits in the address.
+function command_netmask-length {
+    case "$#" in
+        0)
+            echo 1>&2 'Missing <cidr> argument.'
+            return 1
+            ;;
+        1)
+            : # It's good.
+            ;;
+        *)
+            echo 1>&2 'Too many arguments.'
+            return 1
+            ;;
+    esac
+
+    local cidr="$1"
+
+    cidr="$(json-from-any "${cidr}")" \
+    || return "$?"
+
+    jval cidr:json="${cidr}" '$cidr.netmaskBits'
+}
+
 # Command: Print a CIDR.
 function command_print {
     case "$#" in
@@ -615,12 +639,14 @@ if (( ${showHelp} || ${argError} )); then
     echo '  address, and prints the resulting CIDR. This can be used in conjunction'
     echo '  with `widen` to enumerate subnet addresses.'
     echo 'address-length <cidr>'
-    echo '  Prints the length (total number of bits) in the address (not just the'
+    echo '  Prints the length (number of bits) of the address (not just the'
     echo '  netmask).'
     echo 'address-words'
     echo '  Prints the words (16-bit components) of the full address, in a'
     echo '  shell-friendly space-separated decimal form. Note: Even an IPv4'
     echo '  address gets chunked as 16-bit words by this command.'
+    echo 'netmask-length <cidr>'
+    echo '  Prints the length (number of bits) in the netmask.'
     echo 'print <cidr>'
     echo '  Prints a CIDR value.'
     echo 'widen <cidr> <bits>'
