Implement new command `make-subnets`.

diff --git a/src/lib/cidr-calc b/src/lib/cidr-calc
--- a/src/lib/cidr-calc
+++ b/src/lib/cidr-calc
@@ -27,6 +27,20 @@ init-prog
 # Helper functions
 #
 
+# Gets the number of bits needed to represent N values (e.g. the numbers
+# 0..(N-1)).
+function bits-needed {
+    local n="$1"
+    local count=0
+
+    while (( n > 0 )); do
+        (( count++ ))
+        (( n >>= 1 ))
+    done
+
+    echo "${count}"
+}
+
 # Validates and prints out the words (16-bit elements) of an IPv4 address,
 # suitable for subsequent inclusion in a CIDR-JSON result.
 function cidr-address-words-v4 {
@@ -522,6 +536,45 @@ function command_address-words {
     jval --raw cidr:json="${cidr}" '$cidr.address | map(tostring) | join(" ")'
 }
 
+# Command: Print a list of subnets.
+function command_make-subnets {
+    case "$#" in
+        0|1)
+            echo 1>&2 'Missing <cidr> and/or <count> argument.'
+            return 1
+            ;;
+        2)
+            : # It's good.
+            ;;
+        *)
+            echo 1>&2 'Too many arguments.'
+            return 1
+            ;;
+    esac
+
+    local cidr="$1"
+    local count="$2"
+
+    cidr="$(json-from-any "${cidr}")" \
+    || return "$?"
+
+    count="$(parse-number "${count}" 1 65535)" \
+    || return "$?"
+
+    cidr="$(command_widen "${cidr}" "$(bits-needed "${count}")")" \
+    || return "$?"
+
+    local result=()
+
+    local n
+    for (( n = 0; n < count; n++ )); do
+        result+=("$(command_add-to-network "${cidr}" "${n}")") \
+        || return "$?"
+    done
+
+    jarray "${result[@]}"
+}
+
 # Command: Gets the total number of bits in the address.
 function command_netmask-length {
     case "$#" in
@@ -728,9 +781,21 @@ fi
 result="$("${commandFunc}" "$@")" \
 || exit "$?"
 
-if [[ ${result} =~ ^'{' ]]; then
-    # A JSON result is interpreted as a CIDR, in which case the output style
-    # matters.
+case "${result}" in
+    '['*)
+        resultType=array
+        ;;
+    '{'*)
+        resultType=object
+        ;;
+     *)
+        resultType=text
+        ;;
+esac
+
+if [[ ${resultType} != 'text' ]]; then
+    # A JSON result is interpreted as a CIDR or list thereof, in which case the
+    # output style matters.
     case "${outputStyle}" in
         compact-json)
             jval --compact result:json="${result}" '$result'
@@ -739,10 +804,19 @@ if [[ ${result} =~ ^'{' ]]; then
             jval result:json="${result}" '$result'
             ;;
         string)
-            cidr-from-json "${result}"
+            if [[ ${resultType} == 'object' ]]; then
+                cidr-from-json "${result}"
+            else
+                # It's an array. Compactly print each element on a line by
+                # itself, then split by lines to convert each object.
+                jval --compact result:json="${result}" '$result[]' \
+                | while read -r line; do
+                    cidr-from-json "${line}"
+                done
+            fi
             ;;
     esac
 else
-    # Not a CIDR. Just print the result.
+    # Arbitrary text and not a CIDR or list of same. Just print the result.
     echo "${result}"
 fi
