New commands `add-to-network` and `address-words`.

diff --git a/src/lib/cidr-calc b/src/lib/cidr-calc
--- a/src/lib/cidr-calc
+++ b/src/lib/cidr-calc
@@ -118,6 +118,91 @@ function command_add-subnet {
         }'
 }
 
+# Command: Add a value to the network address.
+function command_add-to-network {
+    case "$#" in
+        0|1)
+            echo 1>&2 'Missing <cidr> and/or <amount> argument.'
+            return 1
+            ;;
+        2)
+            : # It's good.
+            ;;
+        *)
+            echo 1>&2 'Too many arguments.'
+            return 1
+            ;;
+    esac
+
+    local cidr="$1"
+    local amount="$2"
+
+    cidr="$(json-from-any "${cidr}")" \
+    || return "$?"
+
+    if ! [[ "${amount}" =~ ^(0|([1-9][0-9]{0,5}))$ ]]; then
+        echo 1>&2 'Invalid <amount> argument.'
+        return 1
+    fi
+
+    local address=($(command_address-words "${cidr}"))
+    local netmaskBits="$(jval cidr:json="${cidr}" '$cidr.netmaskBits')"
+
+    # Add the amount at the bottom of the network, that is, at the word which
+    # has the last bit of the network and shifted appropriately so that lower
+    # bits aren't affected.
+    local at="$(( (${netmaskBits} - 1) / 16 ))"
+    local partialShift="$(( (16 - (${netmaskBits} % 16)) % 16 ))"
+    address[${at}]="$(( ${address[${at}]} + (${amount} << ${partialShift}) ))"
+
+    # Perform overflow to higher-order words as necessary.
+    while (( (${at} > 0) && (${address[${at}]} > 0xffff) )); do
+        local at1="$(( ${at} - 1 ))"
+        local v="${address[${at}]}"
+        address[${at}]="$(( ${v} & 0xffff ))"
+        address[${at1}]="$(( ${address[${at1}]} + (${v} >> 16) ))"
+        (( at-- ))
+    done
+
+    if (( ${address[0]} > 0xffff )); then
+        echo 1>&2 "<amount> too large; address overflowed."
+        return 1
+    fi
+
+    jval \
+        cidr:json="${cidr}" \
+        address:json="$(lib json-array "${address[@]}")" \
+        '{
+            type: $cidr.type,
+            address: $address,
+            netmaskBits: $cidr.netmaskBits
+        }'
+}
+
+# Command: Gets the words of the address.
+function command_address-words {
+    case "$#" in
+        0)
+            echo 1>&2 'Missing <cidr> argument.'
+            return 1
+            ;;
+        1)
+            : # It's good.
+            ;;
+        *)
+            echo 1>&2 'Too many arguments.'
+            return 1
+            ;;
+    esac
+
+    local cidr="$1"
+
+    cidr="$(json-from-any "${cidr}")" \
+    || return "$?"
+
+    jval --raw cidr:json="${cidr}" '$cidr.address | map(tostring) | join(" ")'
+}
+
 # Command: Print a CIDR.
 function command_print {
     case "$#" in
@@ -330,6 +415,14 @@ if (( ${showHelp} || ${argError} )); then
     echo '  the given address value. The address must be either a decimal integer'
     echo '  or `::` followed by a hexadecimal integer; and it must fit in the'
     echo '  specified number of bits.'
+    echo 'add-to-network <cidr> <amount>'
+    echo '  Adds the given amount (a positive decimal integer) to the network'
+    echo '  address. This can be used in conjunction with `widen` to enumerate'
+    echo '  subnet addresses.'
+    echo 'address-words'
+    echo '  Prints the words (16-bit components) of the full address, in a'
+    echo '  shell-friendly space-separated decimal form. Note: Even an IPv4'
+    echo '  address gets chunked as 16-bit words by this command.'
     echo 'print <cidr>'
     echo '  Prints a CIDR value.'
     echo 'total-bits <cidr>'
