Make it possible to put sources in assignments. Document intent with `--env`.

diff --git a/bin/secret-access b/bin/secret-access
--- a/bin/secret-access
+++ b/bin/secret-access
@@ -20,20 +20,26 @@ function usage {
       may eventually grow to handle other things), meant to avoid tainting the
       rest of the system with details of how secrets are retrieved.
 
-      The <assignment> syntax is `<name>=<path>` where `name` is the name to
-      assign, and `path` is the URI-like path to the secret in whatever container
-      it comes from. Alternatively, the form `<name>` (no `=` or right-hand-side)
-      is short for `<name>=<name>`.
+      The <assignment> syntax is `<name>`, `<name>=<path>`, or
+      `<name>=<source> <path>`, where <name> is the name to assign, <source> is a
+      source (as in the option of the same name, described below), and <path> is
+      the URI-like path to the secret in whatever container it comes from. The
+      form `<name>` (no `=` or right-hand-side) is short for `<name>=<name>`.
 
+    --env
+      Scans all environment variables for values of the form `<source>` or
+      `<source> <path>` (space separated), adding those to the (possibly empty)
+      assignments.
     --output=<style>
       `eval` -- Output an `eval`able script to set the values.
       `json` -- Output a JSON object with bindings for all requested secrets.
         This is the default.
     --source=<origin>
-      Container to retrieve from. This is required.
+      Container to retrieve from. This is required if any sources are omitted from
+      the assignments.
       `1password:<vault>/<record>` -- Names a 1Password vault and record to
         retrieve from. The path can be arbitrarily deep.
-      (other sources may be defined later)
+      (Other sources may be defined later.)
 
     ${name} [--help | -h]
       Displays this message.
@@ -45,37 +51,45 @@ function usage {
 # Want help?
 opt-action --call='{ usage }' help/h
 
+opt-toggle --var=doEnv env
+
 opt-value --var=outputStyle --init='json' --enum='eval json' output
 
-opt-value --required --var=source --filter='/^[a-z0-9]+:[-_/a-zA-Z0-9]+$/' source
+opt-value --var=source --filter='/^[-_.:/a-zA-Z0-9]+$/' source
 
-# List of variable assignments, as parallel arrays of name and value.
+# List of variable assignments, as parallel arrays.
 varNames=()
-varValues=()
+varSources=()
+varPaths=()
 
-rest-arg --call=parse-rest --filter='/^[_a-zA-Z0-9]+(=[-_.:/a-zA-Z0-9]+)?$/' assignments
+rest-arg --call=parse-rest \
+    --filter='/^[_a-zA-Z0-9]+(=[-_.:/a-zA-Z0-9]+( [-_.:/a-zA-Z0-9]+)?)?$/' \
+    assignments
 function parse-rest {
-    if (( $# == 0 )); then
-        error-msg 'Need one or more assignment arguments.'
-        return 1
-    fi
-
     # Parse assignments.
     while (( $# > 0 )); do
         local arg="$1"
 
-        [[ ${arg} =~ ^([^=]+)(=(.*))?$ ]] \
+        [[ ${arg} =~ ^([^=]+)(=([^ ]+ )?([^ ]+))?$ ]] \
         || break
 
         local name="${BASH_REMATCH[1]}"
-        local value="${BASH_REMATCH[3]}"
+        local rhs="${BASH_REMATCH[2]}"
+        local source="${BASH_REMATCH[3]}"
+        local path="${BASH_REMATCH[4]}"
 
-        if [[ ${value} == '' ]]; then
-            value="${name}"
+        if [[ ${rhs} == '' ]]; then
+            path="${name}"
+        fi
+        if [[ ${source} != '' ]]; then
+            # Remove the space at the end.
+            [[ ${source} =~ ^(.*)' '$ ]]
+            source="${BASH_REMATCH[1]}"
         fi
 
         varNames+=("${name}")
-        varValues+=("${value}")
+        varSources+=("${source}")
+        varPaths+=("${path}")
         shift
     done
 }
@@ -96,29 +110,49 @@ function source-1password {
     op read "op://${vaultRecord}/${path}"
 }
 
+# Retrieves a secret.
+function get-secret {
+    local source="$1"
+    local path="$2"
+
+    if ! [[ ${source} =~ ^([^:]+):(.*)$ ]]; then
+        error-msg "Invalid source: ${source}"
+        exit 1
+    fi
+
+    local sourceName="${BASH_REMATCH[1]}"
+    local sourcePath="${BASH_REMATCH[2]}"
+    local sourceFunc="source-${sourceName}"
+    if ! declare -F "${sourceFunc}" >/dev/null; then
+        error-msg "Unrecognized source: ${sourceName}"
+        exit 1
+    fi
+
+    "${sourceFunc}" "${sourcePath}" "${path}"
+}
+
 
 #
 # Main script
 #
 
-if ! [[ ${source} =~ ^([^:]+):(.*)$ ]]; then
-    error-msg "Invalid source: ${source}"
-    exit 1
-fi
-sourceType="${BASH_REMATCH[1]}"
-sourcePath="${BASH_REMATCH[2]}"
-
-sourceFunc="source-${sourceType}"
-if ! declare -F "${sourceFunc}" >/dev/null; then
-    error-msg "Unrecognized source: ${sourceType}"
+if (( !doEnv && ${#varNames[@]} == 0 )); then
+    error-msg 'Need one or more assignment arguments.'
     exit 1
 fi
 
+varValues=()
 for (( i = 0; i < ${#varNames[@]}; i++ )); do
-    value="${varValues[${i}]}"
-    value="$("${sourceFunc}" "${sourcePath}" "${value}")" \
+    if [[ ${varSources[$i]} == '' ]]; then
+        if [[ ${source} == '' ]]; then
+            error-msg 'Must use --source when making non-source assignments.'
+            exit 1
+        fi
+        varSources[$i]="${source}"
+    fi
+    value="$(get-secret "${varSources[$i]}" "${varPaths[$i]}")" \
     || exit "$?"
-    varValues[${i}]="${value}"
+    varValues[$i]="${value}"
 done
 
 case "${outputStyle}" in
