Rework how zones are specified.

diff --git a/bin/ssh-instance b/bin/ssh-instance
--- a/bin/ssh-instance
+++ b/bin/ssh-instance
@@ -20,9 +20,10 @@ function usage {
       Logs into the indicated instance (by name or IP address), either
       interactively or to execute a command.
 
-      The <instance> can be specified as a DNS name, an IP address, or the form
-      `<region-or-zone>:<name>`. The last option indicates that the instance
-      is to be looked up by its AWS `Name` tag.
+      The <instance> can be specified as a DNS name, an IP address, instance name
+      suffixed with `.<region-or-zone>`, or a plain instance name if
+      `--default-loc` is provided. The last two forms are used to look up the
+      instance by its AWS `Name` tag.
 
       If a <user> is not specified, this command will fall back to the default SSH
       behavior (of using `~/.ssh/config` and defaulting to the local userid).
@@ -37,6 +38,9 @@ function usage {
       to the default SSH behavior (of using `~/.ssh/config` and defaulting to
       `~/.ssh/id_*`).
 
+    --default-loc=<zone-or-region>
+      Location to use for instance name lookups, if not present in the instance
+      name.
     --key=<path>
       Filesystem path to the private key (identity file).
     --script
@@ -54,6 +58,9 @@ function usage {
 
 # Want help?
 opt-action --call='{ usage }' help/h
+
+# Default location.
+opt-value --var=defaultLoc --filter='/./' default-loc
 
 # Path to the key file.
 opt-value --var=keyPath --filter='/./' key
@@ -81,6 +88,70 @@ fi
 #
 # Helper functions
 #
+
+# Interprets a `user@host` string, interpreting zone/name lookups by finding
+# instances by name. Prints JSON info of the results, for ultimate
+# recombination.
+function address-info {
+    local orig="$1"
+
+    local userid=''
+    local address="${orig}"
+    local hostPublicKey=''
+
+    # Split off the userid, if present.
+    if [[ ${orig} =~ ^([^@]+)@(.+)$ ]]; then
+        userid="${BASH_REMATCH[1]}"
+        address="${BASH_REMATCH[2]}"
+    fi
+
+    # Split off the final instance component as the location, if there is more
+    # than one component. Then, check to see if it's a valid location before
+    # committing to the parse.
+    local instanceName="${address}"
+    local instanceLoc=''
+    if [[ ${address} =~ ^(.*)[.]([^.]+)$ ]]; then
+        instanceName="${BASH_REMATCH[1]}"
+        instanceLoc="${BASH_REMATCH[2]}"
+        if ! lib parse-location 2>/dev/null "${instanceLoc}"; then
+            # Not actually a location. Revert!
+            instanceName="${address}"
+            instanceLoc=''
+        fi
+    fi
+
+    # Check to see if `instance` is an actual hostname. If not, set the location
+    # to the default if provided or error out.
+    if [[ ${instanceLoc} == '' ]]; then
+        if ! host >/dev/null 2>&1 "${address}"; then
+            if [[ ${defaultLoc} != '' ]]; then
+                instanceLoc="${defaultLoc}"
+            else
+                error-msg "Host not found (and no default location provided): ${address}"
+                exit 1
+            fi
+        fi
+    fi
+
+    # If we have a location, then try to look up the instance.
+    if [[ ${instanceLoc} != '' ]]; then
+        local result
+        result="$(find-instance "${instanceLoc}" "${instanceName}")" \
+        || return "$?"
+        address="$(jget --output=raw "${result}" '.address')"
+        hostPublicKey="$(jget --output=raw "${result}" '.hostPublicKey')"
+    fi
+
+    jval \
+        userid="${userid}" \
+        address="${address}" \
+        hostPublicKey="${hostPublicKey}" \
+        '{
+            userid:        $userid,
+            address:       $address,
+            hostPublicKey: $hostPublicKey
+        }'
+}
 
 # Adds a host public key to the user's `known_hosts` file.
 function authorize-host {
@@ -114,15 +185,10 @@ function find-instance {
     )" \
     || return "$?"
 
-    local hostPublicKey address
-    hostPublicKey="$(jget --output=raw "${infoJson}" '.hostPublicKey // ""')"
-    address="$(jget --output=raw "${infoJson}" '.publicAddress')"
-
-    echo "instance='${address}'"
-
-    if [[ ${hostPublicKey} != '' ]]; then
-        echo "authorize-host '${address}' '${hostPublicKey}'"
-    fi
+    jget "${infoJson}" '{
+        address:       .publicAddress,
+        hostPublicKey: (.hostPublicKey // "")
+    }'
 }
 
 # Finds the indicated secret via `secret-access`, which is presumed to be a
@@ -153,23 +219,20 @@ function find-secret {
 # Main script
 #
 
-user=''
-instance="${userAtInstance}"
-if [[ ${userAtInstance} =~ ^([^@]+)@([^@]+)$ ]]; then
-    user="${BASH_REMATCH[1]}"
-    instance="${BASH_REMATCH[2]}"
-fi
-
-if [[ ${instance} =~ ^([^:]+):([^:]+)$ ]]; then
-    # The instance is in the AWS-lookup form.
-    instanceEval="$(find-instance "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}")" \
-    || exit "$?"
-    eval "${instanceEval}" \
-    || exit "$?"
-fi
-
 if [[ ${secretSourcePath} != '' ]]; then
     keyPath="$(find-secret "${secretSourcePath}")" \
+    || exit "$?"
+fi
+
+addressInfo="$(address-info "${userAtInstance}")" \
+|| exit "$?"
+
+userid="$(jget --output=raw "${addressInfo}" '.userid')"
+address="$(jget --output=raw "${addressInfo}" '.address')"
+hostPublicKey="$(jget --output=raw "${addressInfo}" '.hostPublicKey')"
+
+if [[ ${hostPublicKey} != '' ]]; then
+    authorize-host "${address}" "${hostPublicKey}" \
     || exit "$?"
 fi
 
@@ -185,10 +248,10 @@ if [[ -t 0 ]]; then
     sshCommand+=('-t')
 fi
 
-if [[ ${user} != '' ]]; then
-    sshCommand+=("${user}@${instance}")
+if [[ ${userid} != '' ]]; then
+    sshCommand+=("${userid}@${address}")
 else
-    sshCommand+=("${instance}")
+    sshCommand+=("${address}")
 fi
 
 if (( ${#command[@]} != 0 )); then
