Enable IPv6-only VPCs.

diff --git a/scripts/lib/milky-cloud/add-subnets b/scripts/lib/milky-cloud/add-subnets
--- a/scripts/lib/milky-cloud/add-subnets
+++ b/scripts/lib/milky-cloud/add-subnets
@@ -17,6 +17,9 @@ define-usage $'
     an associated routing table. Upon success, prints a JSON array of all the
     created subnets.
 
+    --[no-]ipv4
+      Include public IPv4 networking. The default is `--ipv4`. (Note: IPv6 usage
+      can be determined by observing the VPC info, but not IPv4.)
     --loc=<region-or-zone>
       What region to make the subnets in. Must be specified. If specified as an
       availability zone, only the region portion matters.
@@ -37,6 +40,9 @@ define-usage $'
 
 # Want help?
 opt-action --call='{ usage; exit }' help/h
+
+# Do public IPv4?
+opt-toggle --var=useIpv4 --init=1 ipv4
 
 # Region, passed as either region per se or availability zone.
 opt-value --required --var=region --filter=region-from-location loc
@@ -96,31 +102,25 @@ vpcInfo="$(lib find-vpc --loc="${region}" --output=json "${vpcNameOrId}")" \
 
 vpcId="$(jget --output=raw "${vpcInfo}" '.id')"
 
-cidr4="$(extractCidr "${vpcInfo}" ipv4)"
-
-if [[ ${cidr4} == 'many' ]]; then
-    error-msg 'Sorry, cannot deal with multiple CIDRs (IPv4).'
-    exit 1
+cidr4='none'
+v4Subnets=()
+if (( useIpv4 )); then
+    cidr4="$(extractCidr "${vpcInfo}" ipv4)"
+    if [[ ${cidr4} == 'many' ]]; then
+        error-msg 'Sorry, cannot deal with multiple CIDRs (IPv4).'
+        exit 1
+    fi
+    v4Subnets=($(lib cidr-calc make-subnets "${cidr4}" "${#azList[@]}"))
 fi
 
 cidr6="$(extractCidr "${vpcInfo}" ipv6)"
-
+v6Subnets=()
 if [[ ${cidr6} == 'many' ]]; then
     error-msg 'Sorry, cannot deal with multiple CIDRs (IPv6).'
     exit 1
-fi
-
-azCount="${#azList[@]}"
-v4Subnets=()
-v6Subnets=()
-
-if [[ ${cidr4} != 'none' ]]; then
-    v4Subnets=($(lib cidr-calc make-subnets "${cidr4}" "${azCount}"))
-fi
-
-if [[ ${cidr6} != 'none' ]]; then
+elif [[ ${cidr6} != 'none' ]]; then
     # `64` because AWS requires V6 subnet networks to be exactly 64 bits.
-    v6Subnets=($(lib cidr-calc make-subnets "${cidr6}" "${azCount}" 64))
+    v6Subnets=($(lib cidr-calc make-subnets "${cidr6}" "${#azList[@]}" 64))
 fi
 
 if [[ ${name} == '' ]]; then
