Improve error output.

diff --git a/scripts/lib/milky-cloud/secret-access b/scripts/lib/milky-cloud/secret-access
--- a/scripts/lib/milky-cloud/secret-access
+++ b/scripts/lib/milky-cloud/secret-access
@@ -105,8 +105,14 @@ function source-1password {
     local vaultRecord="$1"
     local path="$2"
 
+    local opUrl="op://${vaultRecord}/${path}"
     # Note: `op` is the (very poorly named) 1Password CLI.
-    op read "op://${vaultRecord}/${path}"
+    op read "op://${vaultRecord}/${path}" \
+    || {
+        error-msg 'Could not read 1Password secret:'
+        error-msg "  ${opUrl}"
+        return 1
+    }
 }
 
 # Retrieves a secret.
