Extract most of the function body generator.

diff --git a/bin/lib/arg-processor b/bin/lib/arg-processor
--- a/bin/lib/arg-processor
+++ b/bin/lib/arg-processor
@@ -607,52 +607,74 @@ function _argproc_define-value-required-arg {
         handlerName="_argproc:positional-${longName}"
     fi
 
-    if [[ ${callFunc} != '' ]]; then
-        # Re-form as the caller code.
-        callFunc="${callFunc}"' "$1" || return "$?"'
-    fi
-
-    if [[ ${varName} != '' ]]; then
-        # Re-form as the setter code.
-        varName="${varName}"'="$1"'
-    fi
-
-    if [[ ${filter} =~ ^/(.*)/$ ]]; then
-        # Re-form `filter` as the statement which performs the regex check.
-        filter="${BASH_REMATCH[1]}"
-        filter='
-            if ! [[ $1 =~ '"${filter}"' ]]; then
-                echo 1>&2 "Invalid value for '"${desc}"': ${_argproc_value}"
-                return 1
-            fi'
-    elif [[ ${filter} =~ ^\{(.*)\}$ ]]; then
-        # Re-form `filter` as the code block to run.
-        filter="$(printf '{\n%s\n} || return "$?"\n' "${BASH_REMATCH[1]}")"
-    elif [[ ${filter} != '' ]]; then
-        # Re-form `filter` as the call to the filter function. Note: We can't
-        # do `set "$(...)"` or assign on the `local` line, because either of
-        # those will swallow a failure from the call.
-        filter="$(printf '
-            local _argproc_value
-            _argproc_value="$(%s "$1")" || return 1
-            set "${_argproc_value}"
-            ' "${filter}")"
-    fi
+    local handlerBody="$(
+        _argproc_handler-body "${longName}" "${filter}" "${callFunc}" "${varName}"
+    )"
 
     eval 'function '"${handlerName}"' {
         if (( $# < 1 )); then
             echo 1>&2 "Value required for '"${desc}"'."
             return 1
         fi
-        '"${filter}"'
-        '"${callFunc}"'
-        '"${varName}"'
-        _argproc_receivedArgNames+="<'"${longName}"'>"
+        '"${handlerBody}"'
     }'
 
     if [[ ${abbrevChar} != '' ]]; then
         _argproc_define-abbrev "${abbrevChar}" "${longName}"
     fi
+}
+
+# Produce an argument handler body, from the given components.
+function _argproc_handler-body {
+    local longName="$1"
+    local filter="$2"
+    local callFunc="$3"
+    local varName="$4"
+    local result=()
+
+    if [[ ${filter} =~ ^/(.*)/$ ]]; then
+        # Add a statement which performs the regex check.
+        filter="${BASH_REMATCH[1]}"
+        result+=(
+            'if ! [[ $1 =~ '"${filter}"' ]]; then
+                echo 1>&2 "Invalid value for '"${desc}"': $1"
+                return 1
+            fi'
+        )
+    elif [[ ${filter} =~ ^\{(.*)\}$ ]]; then
+        # Add a compound statement for the code block.
+        result+=(
+            "$(printf '{\n%s\n} || return "$?"\n' "${BASH_REMATCH[1]}")"
+        )
+    elif [[ ${filter} != '' ]]; then
+        # Add a call to the filter function. Note: We can't do `set "$(...)"` or
+        # assign in the `local` statement, because either of those will swallow
+        # a failure from the call.
+        result+=(
+            "$(printf '
+                local _argproc_value; _argproc_value="$(%s "$1")" || return 1
+                set "${_argproc_value}"' \
+                "${filter}")"
+        )
+    fi
+
+    if [[ ${callFunc} != '' ]]; then
+        result+=(
+            "$(printf '%s "$1" || return "$?"' "${callFunc}")"
+        )
+    fi
+
+    if [[ ${varName} != '' ]]; then
+        result+=(
+            "$(printf '%s="$1"' "${varName}")"
+        )
+    fi
+
+    result+=(
+        "$(printf '_argproc_receivedArgNames+="<%s>"' "${longName}")"
+    )
+
+    printf '%s\n' "${result[@]}"
 }
 
 # Janky yet reasonable argument parser for the commands in this library. (How
