Use `arg-processor`.

diff --git a/bin/lib/parse-location b/bin/lib/parse-location
--- a/bin/lib/parse-location
+++ b/bin/lib/parse-location
@@ -20,24 +20,29 @@ function usage {
     print-usage $'
     Usage:
 
-    ${name} <zone-or-region>
+    ${name} [<opt> ...] <zone-or-region>
       Parses a location -- a region or availability zone -- and if
       valid then optionally prints out one of the components. Note that
       only one each `--input-` and `--print-` option has any effect (the
       last specified).
 
-      --input-zone
-        Require an availibility zone as input.
+      --input-any
+        Accept either an availability zone or a region as input. This is the
+        default.
       --input-region
         Require a region as input.
+      --input-zone
+        Require an availibility zone as input.
+      --print-none
+        Do not print anything. This is the default.
       --print-region
         Print the parsed region.
       --print-zone
-        Print the full zone (which will be the same as the input).
-        Implies `--input-zone`.
+        Print the full zone (which will be the same as the input). Implies
+        `--input-zone`.
       --print-zone-suffix
-        Print the zone suffix (everything after the region).
-        Implies `--input-zone`.
+        Print the zone suffix (everything after the region). Implies
+        `--input-zone`.
 
     ${name} [--help | -h]
       Displays this message.
@@ -46,73 +51,37 @@ function usage {
     exit "$1"
 }
 
-# Error during argument processing?
-argError=0
+# Want help?
+opt-action --call=usage --value=0 help/h
+
+# Required input type.
+opt-choice --var=inputType --default=input-any \
+    input-any input-region input-zone
+
+# Item to print.
+opt-choice --var=printItem --default=print-none \
+    print-none print-region print-zone print-zone-suffix
 
 # Location (availability zone or region).
 inLocation=''
+rest-arg --call=parse-rest
+function parse-rest {
+    if (( $# < 1 )); then
+        echo 1>&2 'Missing argument: <zone-or-region>'
+        return 1
+    elif (( $# > 1 )); then
+        echo 1>&2 'Too many arguments.'
+        return 1
+    fi
 
-# Required input type.
-inputType='any'
-
-# Desired output.
-printItem='none'
-
-while (( $# > 0 )); do
-    case "$1" in
-        --input-region)
-            inputType='region'
-            ;;
-        --input-zone)
-            inputType='zone'
-            ;;
-        --print-region)
-            printItem='region'
-            ;;
-        --print-zone)
-            printItem='zone'
-            ;;
-        --print-zone-suffix)
-            printItem='zone-suffix'
-            ;;
-        -h|--help)
-            argError=-1 # `-1` suppresses error exit after displaying usage.
-            break
-            ;;
-        --)
-            # Explicit end of options.
-            shift
-            break
-            ;;
-        -?*)
-            echo 1>&2 "Unknown option: $1"
-            argError=1
-            break
-            ;;
-        *)
-            # Non-option argument.
-            break
-            ;;
-    esac
-
-    shift
-done
-
-if [[ ${printItem} =~ ^zone ]]; then
-    # Don't allow region input if we are to print a zone-ish thing.
-    inputType='zone'
-fi
-
-if (( $# < 1 )); then
-    echo 1>&2 'Missing argument: zone or region'
-    argError=1
-else
     inLocation="$1"
-    shift
-fi
+}
 
-if (( argError )); then
-    usage "${argError}"
+process-args "$@" || usage "$?"
+
+if [[ ${printItem} =~ ^print-zone ]]; then
+    # Don't allow region input if we are to print a zone-ish thing.
+    inputType='input-zone'
 fi
 
 
@@ -131,29 +100,29 @@ zoneSuffix="${BASH_REMATCH[2]}"
 
 # Validate the required input type, if needed.
 case "${inputType}" in
-    region)
+    input-region)
         if [[ ${zoneSuffix} != '' ]]; then
             echo 1>&2 'Region input required; got zone.'
             exit 1
         fi
         ;;
-    zone)
-    if [[ ${zoneSuffix} == '' ]]; then
-        echo 1>&2 'Zone input required; got region.'
-        exit 1
-    fi
-    ;;
+    input-zone)
+        if [[ ${zoneSuffix} == '' ]]; then
+            echo 1>&2 'Zone input required; got region.'
+            exit 1
+        fi
+        ;;
 esac
 
 # Output whatever is requested, if anything.
 case "${printItem}" in
-    region)
+    print-region)
         echo "${region}"
         ;;
-    zone)
+    print-zone)
         echo "${inLocation}"
         ;;
-    zone-suffix)
+    print-zone-suffix)
         echo "${zoneSuffix}"
         ;;
 esac
