Use `arg-processor`.

diff --git a/bin/lib/region-from-zone b/bin/lib/region-from-zone
--- a/bin/lib/region-from-zone
+++ b/bin/lib/region-from-zone
@@ -30,52 +30,29 @@ function usage {
     exit "$1"
 }
 
-# Error during argument processing?
-argError=0
+# Want help?
+opt-action --call=usage --value=0 help/h
 
-# Location (availability zone).
-inLocation=''
+# Availability zone.
+inZone=''
+rest-arg --call=parse-rest
+function parse-rest {
+    if (( $# < 1 )); then
+        echo 1>&2 'Missing argument: <zone>'
+        return 1
+    elif (( $# > 1 )); then
+        echo 1>&2 'Too many arguments.'
+        return 1
+    fi
 
-while (( $# > 0 )); do
-    case "$1" in
-        -h|--help)
-            argError=-1 # `-1` suppresses error exit after displaying usage.
-            break
-            ;;
-        --)
-            # Explicit end of options.
-            shift
-            break
-            ;;
-        -?*)
-            echo 1>&2 "Unknown option: $1"
-            argError=1
-            break
-            ;;
-        *)
-            # Non-option argument.
-            break
-            ;;
-    esac
+    inZone="$1"
+}
 
-    shift
-done
-
-if (( $# < 1 )); then
-    echo 1>&2 'Missing argument: availability zone'
-    argError=1
-else
-    inLocation="$1"
-    shift
-fi
-
-if (( argError )); then
-    usage "${argError}"
-fi
+process-args "$@" || usage "$?"
 
 
 #
 # Main script
 #
 
-lib parse-location --input-zone --print-region "${inLocation}"
+lib parse-location --input-zone --print-region "${inZone}"
