WIP on `wait-until-running`.

diff --git a/scripts/lib/milky-cloud/instance/wait-until-running b/scripts/lib/milky-cloud/instance/wait-until-running
--- a/scripts/lib/milky-cloud/instance/wait-until-running
+++ b/scripts/lib/milky-cloud/instance/wait-until-running
@@ -46,9 +46,133 @@ process-args "$@" || usage --short
 
 
 #
+# Helper functions
+#
+
+# Wait for just one instance.
+function wait-for-one {
+    info-msg TODO
+    return 1
+}
+
+# Wait implementation, plugged into the control skeleton.
+function wait-impl {
+    local ids
+    local loc
+
+    while (( $# > 0 )); do
+        case "$1" in
+            --ids=*)   ids="${1#*=}"   ;;
+            --loc=*)   loc="${1#*=}"   ;;
+            *)
+                error-msg $'Shouldn\'t happen!'
+                return 1
+        esac
+        shift
+    done
+
+    # Convert `ids` to a regular array.
+    ids=($(jget --output=raw "${ids}" '.[]'))
+
+    local id trouble=()
+    for id in "${ids[@]}"; do
+        if ! wait-for-one "${id}"; then
+            trouble+=("${id}")
+        fi
+    done
+
+    if (( ${#trouble[@]} != 0 )); then
+        error-msg 'Trouble with:'
+        error-msg --exec printf '  %s\n' "${trouble[@]}"
+        return 1
+    fi
+}
+
+
+#
 # Main script
 #
 
+instance-control-skeleton 'Waiting for running' wait-impl
+
+exit 1
+#########################################
+# OLD STUFF
 # TODO
 info-msg TODO
 exit 1
+
+progress-msg 'Waiting for instance to be running...'
+
+local infoJson
+
+local state
+while true; do
+    infoJson="$(find-prod-instance --json "${name}")" || return "$?"
+
+    if [[ ${infoJson} == '' ]]; then
+        error-msg "Cannot wait for ${name}; no such instance."
+        return 1
+    fi
+
+    state="$(jget --output=raw "${infoJson}" '.state')"
+    if [[ ${state} != 'pending' ]]; then
+        break
+    fi
+
+    sleep 1
+done
+
+if [[ ${state} != 'running' ]]; then
+    error-msg "Instance ${name} in state ${state}; cannot become running."
+    return 1
+fi
+
+# Use `ssh-keyscan` to see if (a) we can connect to SSH, and (b) we get our
+# expected host key. If we can't connect, fail on that front. If we connect
+# and see the wrong key, wait a moment and try again because that means that
+# the initial boot is still ongoing.
+
+progress-msg 'Waiting for first boot to complete...'
+
+local address="$(jget --output=raw "${infoJson}" '.publicAddress')"
+local expectedKey="$(jget --output=raw "${infoJson}" '.hostPublicKey')"
+
+local tries=30
+local success=0
+local responsive=0
+local shownKeyMsg=0
+while (( !success && (tries-- > 0) )); do
+    local gotKey="$(
+        # `-T 60` == one minute timeout. `awk` to print just the key.
+        ssh-keyscan 2>/dev/null -T 60 -t ed25519 "${address}" \
+        | awk '{print $2, $3}'
+    )"
+
+    if [[ ${gotKey} == ${expectedKey} ]]; then
+        success=1
+    elif [[ ${gotKey} == '' ]]; then
+        # Host is apparently unreachable, or it might be _almost_ ready.
+        error-msg 'Still waiting for first boot to complete...'
+        sleep 1
+    else
+        responsive=1
+        if (( !shownKeyMsg )); then
+            progress-msg 'Waiting for correct host key...'
+            shownKeyMsg=1
+        fi
+        sleep 1
+    fi
+done
+
+if (( !success )); then
+    if (( responsive )); then
+        error-msg "Instance ${name} is running and responsive,"
+        error-msg "but boot seems to be incomplete. Alas!"
+    else
+        error-msg "Instance ${name} did not complete its first boot. Alas!"
+    fi
+    return 1
+fi
+
+progress-msg 'Done!'
