Fix bugs; _mostly_ working!

diff --git a/src/add-internet-gateway b/src/add-internet-gateway
--- a/src/add-internet-gateway
+++ b/src/add-internet-gateway
@@ -144,10 +144,11 @@ inRegion="$(lib region-from-location "${inLocation}")" \
 || exit "$?"
 
 # Validate the VPC name/id and get its info, extracting a couple useful bits.
-vpcInfo="$(lib find-vpc --in="${inRegion}" "${vpcNameOrId}")" \
+vpcInfo="$(lib find-vpc --print-all --in="${inRegion}" "${vpcNameOrId}")" \
 || exit "$?"
 
-vpcId="$(jget "${vpcInfo}" '.VpcId')"
+echo 1>&2 '########### HMMMMMMM'
+vpcId="$(jget --raw "${vpcInfo}" '.VpcId')"
 usesIpv4="$(jget "${vpcInfo}" \
     'if .CidrBlockAssociationSet == null then 0 else 1 end')"
 usesIpv6="$(jget "${vpcInfo}" \
@@ -182,7 +183,7 @@ rtId="$(ec2-json describe-route-tables \
     '$filters' \
     :: --raw '.RouteTables[0].RouteTableId'
 )" \
-&& echo 1>&2 "Default VPC route table: ${rtId}"
+&& echo 1>&2 "Default VPC route table: ${rtId}" \
 || error=1
 
 # Attach the internet gateway to the VPC.
@@ -201,15 +202,17 @@ if (( !error )); then
     || error=1
 fi
 
-# TODO: Add all the appropriate routes.
+# Add an IPv4 route if appropriate.
 v4RouteAdded=0
 if (( !error && usesIpv4 )); then
     ec2-json create-route \
         --in="${inRegion}" \
+        gatewayId="${gatewayId}" \
         rtId="${rtId}" \
         '{
             RouteTableId: $rtId,
-            DestinationCidrBlock: "0.0.0.0/0"
+            DestinationCidrBlock: "0.0.0.0/0",
+            GatewayId: $gatewayId
         }' \
         :: --none \
     && v4RouteAdded=1 \
@@ -217,14 +220,17 @@ if (( !error && usesIpv4 )); then
     || error=1
 fi
 
+# Add an IPv6 route if appropriate.
 v6RouteAdded=0
 if (( !error && usesIpv6 )); then
     ec2-json create-route \
         --in="${inRegion}" \
+        gatewayId="${gatewayId}" \
         rtId="${rtId}" \
         '{
             RouteTableId: $rtId,
-            DestinationIpv6CidrBlock: "::/0"
+            DestinationIpv6CidrBlock: "::/0",
+            GatewayId: $gatewayId
         }' \
         :: --none \
     && v6RouteAdded=1 \
@@ -238,47 +244,8 @@ error=1
 
 if (( error )); then
     echo 1>&2 'Error(s) after gateway creation. Attempting cleanup!'
-
-    if (( v4RouteAdded )); then
-        echo 1>&2 'Deleting IPv4 route...'
-        ec2-json delete-route \
-            --in="${inRegion}" \
-            rtId="${rtId}" \
-            '{
-                RouteTableId: $rtId,
-                DestinationCidrBlock: "0.0.0.0/0"
-            }'
-    fi
-
-    if (( v6RouteAdded )); then
-        echo 1>&2 'Deleting IPv6 route...'
-        ec2-json delete-route \
-            --in="${inRegion}" \
-            rtId="${rtId}" \
-            '{
-                RouteTableId: $rtId,
-                DestinationIpv6CidrBlock: "::/0"
-            }'
-    fi
-
-    if (( attached )); then
-        echo 1>&2 'Detaching gateway...'
-        ec2-json detach-internet-gateway \
-            --in="${inRegion}" \
-            gatewayId="${gatewayId}" \
-            vpcId="${vpcId}" \
-            '{
-                InternetGatewayId: $gatewayId,
-                VpcId: $vpcId
-            }'
-    fi
-
-    echo 1>&2 'Deleting gateway...'
-    ec2-json delete-internet-gateway \
-        --in="${inRegion}" \
-        gatewayId="${gatewayId}" \
-        '{ InternetGatewayId: $gatewayId }'
-
+    lib delete-internet-gateway --in="${inRegion}" --gateway="${gatewayId}"
+    echo 1>&2 'Done with post-error gateway cleanup.'
     exit "${error}"
 fi
 
