progress

diff --git a/src/aws-preflight b/src/aws-preflight
--- a/src/aws-preflight
+++ b/src/aws-preflight
@@ -69,9 +69,28 @@ fi
 # Main script
 #
 
+error=0
+
 if ! which aws >/dev/null 2>&1; then
     echo 1>&2 'Missing `aws` binary.'
-    exit 1
+    error=1
+fi
+
+if ! which jq >/dev/null 2>&1; then
+    echo 1>&2 'Missing `jq` binary.'
+    error=1
+fi
+
+if [[ ${AWS_ACCESS_KEY_ID} == '' ]]; then
+    echo 1>&2 'Missing `AWS_ACCESS_KEY_ID` environment variable.'
+    error=1
+fi
+
+if [[ ${AWS_SECRET_ACCESS_KEY} == '' ]]; then
+    echo 1>&2 'Missing `AWS_SECRET_ACCESS_KEY` environment variable.'
+    error=1
 fi
 
 # TODO: Should probably do more stuff!
+
+exit "${error}"
