Flesh out a bit; add a couple new scripts.

diff --git a/src/aws-preflight b/src/aws-preflight
--- a/src/aws-preflight
+++ b/src/aws-preflight
@@ -4,7 +4,7 @@
 # Licensed AS IS and WITHOUT WARRANTY under the Apache License,
 # Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
 #
-# This launches a Dan-standard AWS instance.
+# Performs standard preflight checks needed before running AWS commands.
 
 # Set `progName` to the program name, `progDir` to its directory, and `baseDir`
 # to `progDir`'s directory. Follows symlinks.
@@ -32,17 +32,11 @@ argError=0
 # Need help?
 showHelp=0
 
-# Instance type.
-instanceType='t3.nano'
-
 while true; do
     case $1 in
         -h|--help)
             showHelp=1
             break
-            ;;
-        --instance-type=?*)
-            instanceType="$1"
             ;;
         --) # End of all options
             shift
@@ -64,13 +58,11 @@ if (( ${showHelp} || ${argError} )); then
     echo 'Usage:'
     echo ''
     echo "${progName} [<opt> ...]"
-    echo '  Launches a standard-configured instance.'
-    echo ''
-    echo '  --instance-type=<type>'
-    echo '    What type of instance to install. Defaults to `t3.nano`.'
+    echo '  Performs standard preflight checks needed before running AWS'
+    echo '  commands.'
     echo ''
     echo "${progName} [--help | -h]"
-    echo '  Display this message.'
+    echo '  Displays this message.'
     exit ${argError}
 fi
 
@@ -79,19 +71,9 @@ fi
 # Main script
 #
 
-"${progDir}/aws-preflight" || exit "$?"
-
-# Figure out the correct image ID.
-imageId="$(${progDir}/find-image-id --instance-type="${instanceType}")"
-
-if [[ $? != 0 ]]; then
-    exit "$?"
+if ! which aws >/dev/null 2>&1; then
+    echo 1>&2 'Missing `aws` binary.'
+    exit 1
 fi
 
-# Stuff goes here!
-echo '### Stuff goes here!'
-exit 1
-
-aws ec2 run-instances \
-    --image-id="${imageId}" \
-    --instance-type="${instanceType}"
+# TODO: Should probably do more stuff!
diff --git a/src/find-image-id b/src/find-image-id
--- a/src/find-image-id
+++ b/src/find-image-id
@@ -4,7 +4,7 @@
 # Licensed AS IS and WITHOUT WARRANTY under the Apache License,
 # Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
 #
-# This launches a Dan-standard AWS instance.
+# Finds an image ID to use when launching an instance.
 
 # Set `progName` to the program name, `progDir` to its directory, and `baseDir`
 # to `progDir`'s directory. Follows symlinks.
@@ -33,7 +33,7 @@ argError=0
 showHelp=0
 
 # Instance type.
-instanceType='t3.nano'
+instanceType=''
 
 while true; do
     case $1 in
@@ -60,17 +60,22 @@ while true; do
     shift
 done
 
+if [[ ${instanceType} == '' ]]; then
+    echo 1>&2 'Missing option: --instance-type'
+    argError=1
+fi
+
 if (( ${showHelp} || ${argError} )); then
     echo 'Usage:'
     echo ''
     echo "${progName} [<opt> ...]"
-    echo '  Launches a standard-configured instance.'
+    echo '  Finds an image ID to use when launching an instance.'
     echo ''
     echo '  --instance-type=<type>'
-    echo '    What type of instance to install. Defaults to `t3.nano`.'
+    echo '    What type of instance to install. Must be specified.'
     echo ''
     echo "${progName} [--help | -h]"
-    echo '  Display this message.'
+    echo '  Displays this message.'
     exit ${argError}
 fi
 
@@ -82,7 +87,7 @@ fi
 "${progDir}/aws-preflight" || exit "$?"
 
 # Figure out the correct image ID.
-imageId="$(${progDir}/find-image-id --instance-type="${instanceType}")"
+imageId="$(${progDir}/find-image-id)"
 
 if [[ $? != 0 ]]; then
     exit "$?"
@@ -91,7 +96,3 @@ fi
 # Stuff goes here!
 echo '### Stuff goes here!'
 exit 1
-
-aws ec2 run-instances \
-    --image-id="${imageId}" \
-    --instance-type="${instanceType}"
