More flesh. More script.

diff --git a/src/find-image-id b/src/find-image-id
--- a/src/find-image-id
+++ b/src/find-image-id
@@ -3,8 +3,6 @@
 # Copyright 2022 Dan Bornstein.
 # Licensed AS IS and WITHOUT WARRANTY under the Apache License,
 # Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
-#
-# Finds an image ID to use when launching an instance.
 
 # Set `progName` to the program name, `progDir` to its directory, and `baseDir`
 # to `progDir`'s directory. Follows symlinks.
@@ -35,21 +33,27 @@ showHelp=0
 # Instance type.
 instanceType=''
 
+# Location (availability zone).
+inLocation=''
+
 while true; do
     case $1 in
         -h|--help)
             showHelp=1
             break
             ;;
+        --in=?*)
+            inLocation="${1#*=}"
+            ;;
         --instance-type=?*)
-            instanceType="$1"
+            instanceType="${1#*=}"
             ;;
         --) # End of all options
             shift
             break
             ;;
         -?*)
-            echo "Unknown option: $1" 1>&2
+            echo 1>&2 "Unknown option: $1"
             argError=1
             break
             ;;
@@ -60,9 +64,16 @@ while true; do
     shift
 done
 
-if [[ ${instanceType} == '' ]]; then
-    echo 1>&2 'Missing option: --instance-type'
-    argError=1
+if (( !${argError} )); then
+    if [[ ${inLocation} == '' ]]; then
+        echo 1>&2 'Missing option: --in'
+        argError=1
+    fi
+
+    if [[ ${instanceType} == '' ]]; then
+        echo 1>&2 'Missing option: --instance-type'
+        argError=1
+    fi
 fi
 
 if (( ${showHelp} || ${argError} )); then
@@ -71,6 +82,8 @@ if (( ${showHelp} || ${argError} )); then
     echo "${progName} [<opt> ...]"
     echo '  Finds an image ID to use when launching an instance.'
     echo ''
+    echo '  --in=<availability-zone>'
+    echo '    Where to launch. Must be specified.'
     echo '  --instance-type=<type>'
     echo '    What type of instance to install. Must be specified.'
     echo ''
@@ -84,7 +97,19 @@ fi
 # Main script
 #
 
-"${progDir}/aws-preflight" || exit "$?"
+"${progDir}/aws-preflight" \
+|| exit "$?"
+
+inRegion="$(${progDir}/region-from-zone "${inLocation}")" \
+|| exit "$?"
+
+aws ec2 describe-instance-type-offerings \
+    --output=text \
+    --region="${inRegion}" \
+    --location-type=availability-zone \
+    --filters=Name=location,Values="${inLocation}" \
+    --filters=Name=instance-type,Values="${instanceType}" \
+|| exit "$?"
 
 # Stuff goes here!
 echo '### Stuff goes here!'
diff --git a/src/region-from-zone b/src/region-from-zone
--- a/src/region-from-zone
+++ b/src/region-from-zone
@@ -31,22 +31,13 @@ argError=0
 showHelp=0
 
 # Location (availability zone).
-inLocation='us-west-2a'
-
-# Instance type.
-instanceType='t3.nano'
+inLocation=''
 
 while true; do
     case $1 in
         -h|--help)
             showHelp=1
             break
-            ;;
-        --in=?*)
-            inLocation="${1#*=}"
-            ;;
-        --instance-type=?*)
-            instanceType="${1#*=}"
             ;;
         --) # End of all options
             shift
@@ -64,19 +55,22 @@ while true; do
     shift
 done
 
+if [[ $# < 1 ]]; then
+    echo 1>&2 'Missing argument: availability zone'
+    argError=1
+else
+    inLocation="$1"
+    shift
+fi
+
 if (( ${showHelp} || ${argError} )); then
     echo 'Usage:'
     echo ''
-    echo "${progName} [<opt> ...]"
-    echo '  Launches a standard-configured instance.'
-    echo ''
-    echo '  --in=<availability-zone>'
-    echo '    Where to launch.'
-    echo '  --instance-type=<type>'
-    echo '    What type of instance to install.'
+    echo "${progName} <zone>"
+    echo '  Prints the region associated with an availability zone.'
     echo ''
     echo "${progName} [--help | -h]"
-    echo '  Display this message.'
+    echo '  Displays this message.'
     exit ${argError}
 fi
 
@@ -85,20 +79,12 @@ fi
 # Main script
 #
 
-"${progDir}/aws-preflight" || exit "$?"
+# All we really need to do (at least for now) is drop the last character
+# of the zone.
 
-# Figure out the correct image ID.
-imageId="$(${progDir}/find-image-id \
-    --in="${inLocation}" --instance-type="${instanceType}")"
-
-if [[ $? != 0 ]]; then
-    exit "$?"
+if [[ ${inLocation} =~ ^(..*).$ ]]; then
+    echo "${BASH_REMATCH[1]}"
+else
+    echo 1>&2 'Unparseable input.'
+    exit 1
 fi
-
-# Stuff goes here!
-echo '### Stuff goes here!'
-exit 1
-
-aws ec2 run-instances \
-    --image-id="${imageId}" \
-    --instance-type="${instanceType}"
