Also find via security groups.

diff --git a/src/find-vpc b/src/find-vpc
--- a/src/find-vpc
+++ b/src/find-vpc
@@ -77,8 +77,8 @@ if (( ${showHelp} || ${argError} )); then
     echo 'Usage:'
     echo ''
     echo "${progName} [<opt> ...] <name-or-id>"
-    echo '  Finds a VPC by name or validates the existence of one by ID. On'
-    echo '  success, prints the VPC ID.'
+    echo '  Finds a VPC by name or security group ID, or validates the existence'
+    echo '  of one by ID. On success, prints the VPC ID.'
     echo ''
     echo '  --in=<region-or-zone>'
     echo '    Where to look. Must be specified. If specified as an availability'
@@ -89,6 +89,122 @@ if (( ${showHelp} || ${argError} )); then
     exit "${argError}"
 fi
 
+#
+# Helper functions
+#
+
+# Performs a `describe-*` call and passes through the JSON output under the
+# indicated top-level object key.
+function do-describe-call {
+    local commandName="$1"
+    local topKey="$2"
+    local filterName="$3"
+    local nameOrId="$4"
+
+    local awsArgs="$(
+    jq -n \
+        --arg filterName "${filterName}" \
+        --arg nameOrId "${nameOrId}" \
+    '
+        {
+            Filters: [
+                {
+                    Name: $filterName,
+                    Values: [$nameOrId]
+                }
+            ]
+        }
+    ')"
+
+    local awsResult="$(
+    aws ec2 "${commandName}" \
+        --region="${awsRegion}" \
+        --cli-input-json="${awsArgs}" \
+    || echo 'error'
+    )"
+
+    if [[ ${awsResult} == 'error' ]]; then
+        # In this case, `aws` will have spewed an error message of some sort, we
+        # hope!
+        exit 1
+    fi
+
+    jq -n --raw-output \
+        --argjson info "${awsResult}" \
+        --arg topKey "${topKey}" \
+        '$info | .[$topKey]'
+}
+
+# Find a VPC by looking through all the VPCs.
+function find-via-describe-vpcs {
+    local filterName="$1"
+    local nameOrId="$2"
+
+    local awsResult
+    awsResult="$(do-describe-call describe-vpcs Vpcs "${filterName}" "${nameOrId}")" \
+    || exit "$?"
+
+    local vpcId="$(jq -n --raw-output \
+        --argjson info "${awsResult}" \
+    '
+        $info
+        |
+        if length == 0 then "vpc-none"
+        elif length == 1 then .[0].VpcId
+        else "vpc-ambiguous"
+        end
+    ')"
+
+    if [[ ${vpcId} == 'vpc-none' ]]; then
+        echo 1>&2 'No such VPC.'
+        exit 1
+    elif [[ ${vpcId} == 'vpc-ambiguous' ]]; then
+        echo 1>&2 'Ambiguous name or ID matches all of:'
+        jq 1>&2 -n --raw-output \
+            --argjson info "${awsResult}" \
+        '
+            $info | .[] | "  " + .VpcId
+        '
+        exit 1
+    fi
+
+    echo "${vpcId}"
+}
+
+# Find a VPC from an associated security group.
+function find-via-describe-security-groups {
+    local nameOrId="$1"
+
+    local awsResult
+    awsResult="$(do-describe-call describe-security-groups SecurityGroups group-id "${nameOrId}")" \
+    || exit "$?"
+
+    vpcId="$(jq -n --raw-output \
+        --argjson info "${awsResult}" \
+    '
+        $info
+        |
+        if length == 0 then "vpc-none"
+        elif length == 1 then .[0].VpcId
+        else "vpc-ambiguous"
+        end
+    ')"
+
+    if [[ ${vpcId} == 'vpc-none' ]]; then
+        echo 1>&2 'No such VPC.'
+        exit 1
+    elif [[ ${vpcId} == 'vpc-ambiguous' ]]; then
+        echo 1>&2 'Unexpected, Ambiguous security group ID matches all of:'
+        jq 1>&2 -n --raw-output \
+            --argjson info "${awsResult}" \
+        '
+            $info | .[] | "  " + .VpcId
+        '
+        exit 1
+    fi
+
+    echo "${vpcId}"
+}
 
 #
 # Main script
@@ -100,67 +216,13 @@ fi
 awsRegion="$("${progDir}/region-from-location" "${inLocation}")" \
 || exit "$?"
 
-# aws ec2 describe-vpcs ...
-
 if [[ ${nameOrId} =~ ^vpc- ]]; then
     # It looks like an ID.
-    filterName='vpc-id'
+    find-via-describe-vpcs 'vpc-id' "${nameOrId}"
+elif [[ ${nameOrId} =~ ^sg- ]]; then
+    # It looks like a security group ID.
+    find-via-describe-security-groups "${nameOrId}"
 else
     # It's expected to be a name.
-    filterName='tag:Name'
+    find-via-describe-vpcs 'tag:Name' "${nameOrId}"
 fi
-
-awsArgs="$(
-jq -n \
-    --arg filterName "${filterName}" \
-    --arg nameOrId "${nameOrId}" \
-'
-    {
-        Filters: [
-            {
-                Name: $filterName,
-                Values: [$nameOrId]
-            }
-        ]
-    }
-')"
-
-awsResult="$(
-aws ec2 describe-vpcs \
-    --region="${awsRegion}" \
-    --cli-input-json="${awsArgs}" \
-|| echo 'error'
-)"
-
-if [[ ${awsResult} == 'error' ]]; then
-    # In this case, `aws` will have spewed an error message of some sort, we
-    # hope!
-    exit 1
-fi
-
-vpcId="$(jq -n --raw-output \
-    --argjson info "${awsResult}" \
-'
-    $info 
-    | .Vpcs
-    | 
-    if length == 0 then "vpc-none"
-    elif length == 1 then .[0].VpcId
-    else "vpc-ambiguous"
-    end
-')"
-
-if [[ ${vpcId} == 'vpc-none' ]]; then
-    echo 1>&2 'No such VPC.'
-    exit 1
-elif [[ ${vpcId} == 'vpc-ambiguous' ]]; then
-    echo 1>&2 'Ambiguous name or ID matches all of:'
-    jq 1>&2 -n --raw-output \
-        --argjson info "${awsResult}" \
-    '
-        $info | .Vpcs | .[] | "  " + .VpcId
-    '
-    exit 1
-fi
-
-echo "${vpcId}"
