WIP.

diff --git a/src/make-vpc b/src/make-vpc
--- a/src/make-vpc
+++ b/src/make-vpc
@@ -139,32 +139,79 @@ if (( !${error} )); then
     || error=1
 fi
 
-# TODO: Finish this!
-error=1
+# Create an internet gateway.
+gatewayId=''
+if (( !${error} )); then
+    gatewayId="$(ec2-json create-internet-gateway \
+        --in="${inRegion}" \
+        "$(lib name-tag-spec internet-gateway "${name}")" \
+        :: --raw '.InternetGateway.InternetGatewayId'
+    )" \
+    && echo "Made internet gateway: ${gatewayId}" \
+    || error=1
+fi
+
+# Attach the internet gateway to the VPC.
+gatewayAttached=0
+if (( !${error} )); then
+    ec2-json attach-internet-gateway \
+        --in="${inRegion}" \
+        gatewayId="${gatewayId}" \
+        vpcId="${vpcId}" \
+        '{
+            InternetGatewayId: $gatewayId,
+            VpcId: $vpcId
+        }' \
+    && echo "Attached internet gateway: ${gatewayId}" \
+    && gatewayAttached=1 \
+    || error=1
+fi
 
 # Create a subnet per availability zone.
 
-# Create an internet gateway.
-
-# Attach the internet gateway to the VPC.
+# TODO: Finish this!
+error=1
 
 # Do cleanup if necessary.
 
 if (( ${error} )); then
     echo 1>&2 'Error(s) after VPC creation. Attempting cleanup!'
 
+    if (( ${gatewayAttached} )); then
+        echo 1>&2 'Detaching internet gateway...'
+        ec2-json detach-internet-gateway \
+            --in="${inRegion}" \
+            gatewayId="${gatewayId}" \
+            vpcId="${vpcId}" \
+            '{
+                InternetGatewayId: $gatewayId,
+                VpcId: $vpcId
+            }'
+    fi
+
+    if [[ ${gatewayId} != '' ]]; then
+        echo 1>&2 'Deleting internet gateway...'
+        ec2-json delete-internet-gateway \
+            --in="${inRegion}" \
+            gatewayId="${gatewayId}" \
+            '{ InternetGatewayId: $gatewayId }'
+    fi
+
     if [[ ${groupId} != '' ]]; then
+        echo 1>&2 'Deleting security group...'
         ec2-json delete-security-group \
             --in="${inRegion}" \
             groupId="${groupId}" \
             '{ GroupId: $groupId }'
     fi
 
+    echo 1>&2 'Deleting VPC...'
     ec2-json delete-vpc \
         --in="${inRegion}" \
         vpcId="${vpcId}" \
         '{ VpcId: $vpcId }'
 
+    echo 1>&2 'Done with post-error cleanup.'
     exit "${error}"
 fi
 
